mysql:
  host: localhost
  port: 3306
  user: root
  pass: password
  db: man10
money:
  tax: 0
  prize: 10
point:
  player1:
    x:
    y:
    z:
    vx:
    vy:
    vz:
  player1:
    x:
    y:
    z:
    vx:
    vy:
    vz:
  death:
    x:
    y:
    z:
    vx:
    vy:
    vz:
